// Code generated by orchestra-plugin registry; DO NOT EDIT.

package registry

import (
	"github.com/orchestra-mcp/framework/app/plugins"
	aiproviders "github.com/orchestra-mcp/ai/providers"
	browserproviders "github.com/orchestra-mcp/browser/providers"
	discordproviders "github.com/orchestra-mcp/discord/providers"
	httpproviders "github.com/orchestra-mcp/http/providers"
	markdownproviders "github.com/orchestra-mcp/markdown/providers"
	mcpproviders "github.com/orchestra-mcp/mcp/providers"
	notifproviders "github.com/orchestra-mcp/notifications/providers"
	panelsproviders "github.com/orchestra-mcp/panels/providers"
	searchproviders "github.com/orchestra-mcp/search/providers"
	settingsproviders "github.com/orchestra-mcp/settings/providers"
	socketproviders "github.com/orchestra-mcp/socket/providers"
	themesproviders "github.com/orchestra-mcp/themes/providers"
	trayproviders "github.com/orchestra-mcp/tray/providers"
	widgetsproviders "github.com/orchestra-mcp/widgets/providers"
)

// AllPlugins returns all auto-discovered plugin instances.
// Import this ONLY from cmd/server/main.go to avoid import cycles.
// Order matters: foundation plugins first, then dependents.
func AllPlugins() []plugins.Plugin {
	return []plugins.Plugin{
		settingsproviders.NewSettingsPlugin(),
		themesproviders.NewThemesPlugin(),
		notifproviders.NewNotificationsPlugin(),
		httpproviders.NewHttpPlugin(),
		socketproviders.NewSocketPlugin(),
		searchproviders.NewSearchPlugin(),
		markdownproviders.NewMarkdownPlugin(),
		trayproviders.NewTrayPlugin(),
		panelsproviders.NewPanelsPlugin(),
		widgetsproviders.NewWidgetsPlugin(),
		browserproviders.NewBrowserPlugin(),
		aiproviders.NewAiPlugin(),
		discordproviders.NewDiscordPlugin(),
		mcpproviders.NewMcpPlugin(),
	}
}
