name: Feature Request
description: Suggest a new feature for Orchestra MCP
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like to see.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature belong to?
      options:
        - Go Backend (app/, cmd/)
        - Plugin Runtime (app/plugins/)
        - MCP Plugin (plugins/mcp/)
        - Rust Engine (engine/)
        - Desktop App (resources/desktop/)
        - Chrome Extension (resources/extension/)
        - Web Dashboard (resources/dashboard/)
        - CLI / Build System
        - New Plugin
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: willing
    attributes:
      label: Would you submit a PR?
      description: Would you be willing to implement this feature?
      options:
        - "Yes"
        - "Yes, with guidance"
        - "No"
    validations:
      required: true
