// Code generated by orchestra-plugin registry; DO NOT EDIT.

package config

// RegisteredPlugins returns all auto-discovered plugin constructors.
// Import this from cmd/server/main.go — NOT from app/plugins/.
// Each entry is a func() any that returns a plugins.Plugin.
//
// To avoid import cycles, this file does not import plugin packages
// directly. Instead, registration happens at boot time via
// cmd/server/main.go calling PluginManager.Register().
//
// Use `orchestra-plugin registry` or `go generate ./config/...`
// to regenerate the companion file at config/registry/plugins.go.
func RegisteredPlugins() []any {
	return nil
}
